<HTML>
<HEAD> 
<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="TEXT/HTML; CHARSET=GB2312"> 
<TITLE>上传照片</TITLE> 
<STYLE TYPE="TEXT/CSS"> 
<!-- 
.WHITE12 {FONT-SIZE: 12PT; COLOR: #FFFFFF; TEXT-DECORATION: NONE} 
.BLUE10 {FONT-SIZE: 10PT; COLOR: #99CCFF; TEXT-DECORATION: NONE} 
.BLACK10 {FONT-SIZE: 10PT; TEXT-DECORATION: NONE} 
--> 
</STYLE> 
</HEAD> 
<BODY BGCOLOR="#FFFFFF"> 
<?PHP
IF ($UPLOAD){//如果点击"上传"，则执行此PHP代码部分 
IF ($PICURL=="NONE"){ 
ECHO "你没有上传任何文件."; 
EXIT;//如果没有上传文件，则退出程序 
} 
$V=OPENDIR("IMAGE");
IF ($V==0)
{ MKDIR("IMAGE"); //若目录不存在，则新建一个 
$V=OPENDIR("IMAGE"); //取得目录HANDLE 
}
$UP=COPY("$PICURL","IMAGE/$PICURL_NAME"); //关键一步，将临时文件复制到IMAGE目录下 
IF($UP==1)
{ 
 //文件操作 
$FP=FOPEN("PHOTO.TXT","A");//打开文件，以添加方式写入留言 
//初始化写入内容 
$MYDATE=DATE("Y年M月D日 H:I A"); 
$PHOTONOTE=NL2BR($PHOTONOTE);//将换行字元转成 <BR>。 
$TEXT="照片名：<A HREF='IMAGE/$PICURL_NAME' TARGET='_BLANK'>$PICURL_NAME</A> <BR>照片大小:$PICURL_SIZE BYTE<BR> 照片说明：<BR><SPAN CLASS='BLUE10'>$PHOTONOTE</SPAN><BR> <DIV ALIGN='RIGHT'>上传人: $USER($MYDATE)</DIV><HR>"; 
//写入内容 
FWRITE($FP,$TEXT,STRLEN($TEXT)); //STRLIN计算$TEXT的字串长度 
FCLOSE($FP); 
ECHO "文件上传成功!<BR>"; 
UNLINK ($PICURL); //从临时文件夹中删除档案$PICURL 
CLOSEDIR ($V); //关闭目录HANDLE 
}
ELSE
{ECHO "文件上传失败."; EXIT;} //若上传失败，则退出程序 
}
?> 
<TABLE WIDTH="71%" BORDER="0" CELLSPACING="0" CELLPADDING="0" ALIGN="CENTER"> 
<TR BGCOLOR="#6699FF">
<TD>
<DIV ALIGN="CENTER" CLASS="WHITE12">所有照片</DIV> 
</TD> 
</TR> 
<TR>
<TD CLASS="BLACK10">
<?PHP
//显示以往上传照片信息 
READFILE ("PHOTO.TXT"); 
?>
</TD> 
</TR> 
<TR BGCOLOR="#6699FF">
<TD>
<DIV ALIGN="CENTER" CLASS="WHITE12">上传照片</DIV> 
</TD> 
</TR> 
<TR>
<TD>
<FORM ACTION="UPIMAGE.PHP" METHOD="POST" ENCTYPE="MULTIPART/FORM-DATA" NAME="UL"> 
<!--注意：这里必须加上‘ENCTYPE="MULTIPART/FORM-DATA" ’，否则不会产生上 
传动作-->
<DIV ALIGN="CENTER" CLASS="BLACK10">图片源文件：
<INPUT TYPE="FILE" NAME="PICURL" SIZE="15" ACCEPT="IMAGE/X-PNG,IMAGE/GIF,IMAGE/JPEG"> 
<BR> 
照片说明：(不超过50个字)<BR> 
<TEXTAREA NAME="PHOTONOTE" COLS="50" ROWS="5"></TEXTAREA> 
<BR>上传人： 
<INPUT TYPE="TEXT" NAME="USER" SIZE="10" MAXLENGTH="10"> 
<BR> 
<INPUT TYPE="SUBMIT" NAME="UPLOAD" VALUE="上传"> 
<INPUT TYPE="RESET" NAME="RESET" VALUE="重写"> 
</DIV> 
</FORM> 
<DIV ALIGN="CENTER" CLASS="BLUE10"><A HREF="JAVASCRIPT:HISTORY.BACK()"> 返回</A> </DIV> 
</TD> 
</TR> 
</TABLE> 
</BODY> 
</HTML>